### ISSUE TITLE
News

### ISSUE THREAD

**Issue by Kaijadari** [DoudouPike/support_dev#1]
Ajouter une news en commentaire :

**Comment by faresshank** [comment]
je suis sur les fichiers :
- creation.phtml
- traitement-creation.php

**Comment by Kaijadari** [comment]
Je suis sur:
login.php/phtml et traitement_login. php

**Comment by ZelusRL** [comment]
Yo les gars, je suis désolé mais je me sens pas bien du tout ce matin
J'essayerais de venir cet aprem si ça va mieux, sinon dite moi sur quoi je peux bosser en attendant.

**Comment by Kaijadari** [comment]
Le message est passé.
Si on des trucs à te donner à faire, on te préviendra ici.
Repose toi bien ! =)

**Comment by faresshank** [comment]
Pas de soucis, bon retablissement..

PS: est-ce que tu peux créer un espace membres avec gestion des profils complet, et si possible géré via une base de donnée SQL..
T'es pas obligé, mais ça serait cool :)

**Comment by EquusHumanis** [comment]
blblblbl :dash:

**Comment by Shadownest** [comment]
@ZelusRL Tu viens du coup cet après midi ou pas ? :p
