### ISSUE TITLE
[Opti] login

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/support_dev#3]
Dans le traitement_login, récupérer aussi l'id de l'utilisateur et stocké le dans la $_SESSION, ça vous sera utile sous peu :)

**Comment by Shadownest** [comment]
Toujours dans le traitement_login, vous ne respectez pas l'ordre des étapes !
Pour rappel :
1. Vérification de la présence des variables
2. Vérification de la validité des variables
3. Traitement (requête sql)
4. Redirection

Vous faites actuellement :
1, 3, 2, 4

**Comment by Kaijadari** [comment]
C'est corrigé.
Merci. =)
