### ISSUE TITLE
[Debug] modif

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/support_dev#6]
Dans le fichier : support_dev/controllers/modif.php
Vous utilisez $_GET['id'] sans isset

**Comment by Shadownest** [comment]
Vous pouvez aussi au lieu de faire :
$titre = $thisDbTab["title"];
$objectif = $thisDbTab["goal"];
$contenu = $thisDbTab["content"];
Puis utiliser <?=$titre?>, etc...
Faire :
<?=$thisDbTab['title']?>

**Comment by Kaijadari** [comment]
Corrigé.
