### ISSUE TITLE
[Debug] single

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/support_dev#7]
Dans le fichier : support_dev/controllers/single.php
Vous utilisez $_GET['titre'] sans isset
Ligne 16 le isset($titre, etc...) ne sert à rien, la variable sera de toute façon set, ou une erreur apparaitra avant.
Et au lieu d'utiliser :
$id = $thisDbTab["id"];
$titre = $thisDbTab["title"];
$objectif = $thisDbTab["goal"];
$contenu = $thisDbTab["content"];
$d_creation = $thisDbTab["date"];
$d_modif = $thisDbTab["date_last"];
Vous pouvez directement utiliser la variable $thisDbTab (en la renommant peut être)

**Comment by Kaijadari** [comment]
Corrigé.
