### ISSUE TITLE
[Debug] traitement_delete

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/support_dev#8]
Attention aux 4 étapes du fichier de traitement !
Y'a tout juste le traitement de fait et la redirection, mais par contre les étapes 1 et 2... ?

**Comment by Shadownest** [comment]
Ah et passez les valeurs en $_POST plutôt qu'en $_GET pour une suppression c'est plus sûr :)

**Comment by faresshank** [comment]
Pour moi c'est ok :
- Redirection vers 404 si id non valide.
- copie de l'appel à la DB et déclaration des variables dans fichier delete.php
