### ISSUE TITLE
[Debug] traitement_modif

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/support_dev#9]
Utilisez plutôt la concaténation plutôt que l'insertion de variable dans la requête, c'est plus propre et lisible !
$req = "UPDATE lessons SET title = '$titre', goal = '$objectif', content = '$textBox' WHERE id = $id";
=>
$req = "UPDATE lessons SET title = '".$titre."', goal = '".$objectif."', content = '".$textBox."' WHERE id = ".$id;

(Pareil pour la redirection en bas)

**Comment by faresshank** [comment]
C'est reglé, merci !
